### PR TITLE
Add support for appveyor

### PR DESCRIPTION
**Pull request by erbsenzaehler**
and allow Windows user to download current master via artifacts.

Inspired by: http://talkchess.com/forum3/viewtopic.php?f=7&t=70340

### CODE REVIEW

**Comment by erbsenzaehler** [comment]
Not sure if you want to add this, but this could save a bit of time when people are asking for new builds.

**Comment by lucasart** [comment]
Thanks. This is really awesome, and much appreciated. It's such a pain for me to make windows cross compiles. I'll have a look and merge.

**Comment by lucasart** [comment]
@erbsenzaehler: I don't have access to a Windows machine. I think I setup my Appveyor account correctly. Can you confirm if these compiles work?
https://ci.appveyor.com/project/lucasart/demolito/build/artifacts

I've tried to check my Windows compiles in the past with Wine, and often found out that they were miscompiled in a way that works on wine but not on windows (ie. missing some libraries that were somehow not correctly embedded into the executable with -static).

**Comment by erbsenzaehler** [comment]
Unfortunately the compiles were not fine. When I changed the Hash size the engine exited. 

Several attempts to fix this failed, so I successfully tried msys2. 

The compiles generated by https://github.com/erbsenzaehler/Demolito/commit/86f08c7db3f519b2385c3cbcdf656f9082d581ed work fine on my machine running Windows 10. Unfortunately the builds now require a 3mb dll.

**Comment by lucasart** [comment]
Does it help to replace `_aligned_malloc(hashMB << 20, sizeof(HashEntry))` in hash.c, by `malloc(hashMB << 20)` ?

**Comment by erbsenzaehler** [comment]
It does help and now everything works fine.

I did a small speed comparison between different compiles obtained by appveyor. I used compiles generated with gcc by the mingw and msys2 toolchains and I used clang with mingw backend. (CC="clang --target=x86_64-w64-mingw32 -fuse-ld=lld") It turns out that clang does a great job on Windows, too.

Not sure how these compiles behave in gameplay.


search 12 1 \| tail -1 |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | no_popcnt |   |   |   | popcnt |   |   | pext |   |  
mingw | msys2 | clang |   | mingw | msys2 | clang |   | mingw | msys2 | clang
1776 | 1778 | 1986 |   | 1940 | 2129 | 2081 |   | 2160 | 2226 | 2231
1769 | 1787 | 1987 |   | 1946 | 2129 | 2099 |   | 2159 | 2206 | 2227
1777 | 1788 | 1989 |   | 1950 | 2132 | 2090 |   | 2160 | 2227 | 2229
1776 | 1789 | 1985 |   | 1944 | 2123 | 2096 |   | 2150 | 2224 | 2232
1780 | 1787 | 1992 |   | 1949 | 2114 | 2089 |   | 2149 | 2228 | 2240

Using clang on Windows gives the smallest

**Comment by lucasart** [comment]
Thanks again. This is really helpful.

I still need 16-byte alignment, so `malloc()` isn't good enough. I'll push a patch for that. Really ugly code to emulate the missing `aligned_malloc()` with `malloc()`. But, this is Windows, where ugliness is a feature...

For the appveyor file, I think clang will do fine:
* best ex aequo with msys2 on PEXT (the case that matters)
* very close second on POPCNT
* I don't care about NO_POPCNT performance (pre-historic CPUs...), but clang wins clearly here.

Does clang correctly produce statically linked binaries, or do they still depend on bloated DLL?

**Comment by erbsenzaehler** [comment]
They do not depend on a dll file and the compiles are really neat. Maybe we could find a third person to test them to be 100% sure.

If not for gaming and some old chess engines I would have scrapped Windows from my harddrive,too. I do not understand why people find linux difficult

**Pull request merged**
